serve:
    cd static && cargo build
    dioxus serve

release:
    cd static && cargo build
    dioxus build --release

npm-install:
    cd static/css && npm install

watch-css:
    cd static && cargo watch --watch ../src
