serve:
    dx serve

release:
    dx build --release

npm-install:
    cd css && npm install

build-classes:
    DIOXUS_CLASS_BUILD_PATH="$PWD/css/classes.rs" cargo test --features "web build-classes"
    cargo build
    cd css && cargo build

clear-buffer:
    echo -e -n "\\0033c" && tmux clear-history

watch-classes:
    cargo watch -w src/ -s "just clear-buffer && cargo rustc --lib -- -Awarnings && just build-classes"
