serve:
    cd static && cargo build
    dx serve

release:
    cd static && cargo build
    dx build --release

npm-install:
    cd static/css && npm install

watch-css:
    cd static && cargo watch --watch ../src
